version: '3'

services:
  api:
    build: merlin/api
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./merlin/api:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5000:5000"

  client:
    build: merlin/client
    volumes:
      - ./merlin/client:/frontend
      - node-modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - api
    command: ["npm", "start"]

  nojsxclient:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - '80:80'
    depends_on:
      - api

volumes:
  node-modules:

